# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
    networks:
      - avto

  app:
      build:
        context: ./
        dockerfile: Dockerfile
      image: avto
      container_name: avto-app
      restart: unless-stopped
      working_dir: /var/www/html
      networks:
        - avto

  nginx:
      image: nginx:1.25.2-alpine
      container_name: avto-nginx
      restart: unless-stopped
      ports:
        - 8080:80
      volumes:
        - ./:/var/www/html
        - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
        - avto
networks:
  avto:
    driver: bridge